# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 635e2a7dfd14a5a161150c17f08ce908c1313dae81636ebb8f48a959c219ce7fcf247ab380dbce0c53d68ddb6dd4ec4fe3f83625b6cb86e67e65fb570be1d000

test:
  secret_key_base: abe594006be7f9e43b693a296eb48a1230a56ea9b302af4fb2ec7f71d7bb5992a0e1b1aeb5852fa4bc8622e7d8e9ef655a00eae82556cce099a44f9892250340

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
